---
title: "Final Project Report"
author: "Anjile An, Ashley Kang, Amelia Grant-Alfieri, Divya Bisht"
date: 'Due December 11, 2018'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "90%"
)

library(tidyverse)
library(modelr)
library(mgcv)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Motivation

Unlike many factors we can control in determining our health, outdoor air quality is almost impossible to alter given its ubiquitous nature. We are interested in how environmental determinants of health, especially the short term effects of air quality measures, affect acute health outcomes. This also helps us understand the burden of acute health outcomes especially given our changing climate, and the potential impact of worsening air quality in both urban areas and rural areas. 

Our goal is to illustrate potential health disparities across New York State, the trends in the relationship between air quality and acute health outcomes, and areas (geographically and scientifically) requiring future research.

## Related work
*Anything that inspired you, such as a paper, a web site, or something we discussed in class.*

## Initial questions 
*What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?*

## Data
*Source, scraping method, cleaning, etc - Anjile*

Acknowledge multiple ways of measuring things - days, person-days, ug/m3 etc. Justify! 
- Ozone was not used bc not consistently measured across counties. 


## Exploratory analysis
*Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.*
- Ashley, Div

## Additional analysis
*If you undertake formal statistical analyses, describe these in detail.*
- Model building
- Looked at associations, trends

## Discussion
*What were your findings? Are they what you expect? What insights into the data can you make?*


Limitation
- So many things in air, mixtures, hard to get data on/complicated to analyze. Include in future models.

