---
title: "Meeting Notes with Jeff"
author: "Anjile An, Ashley Kang, Amelia Grant-Alfieri, Divya Bisht"
date: 'Due December 11, 2018'
output: github_document
---

## General Notes

* Documenting process - these are the ones that turned out to be the most interesting

* Keep track of all the work we're doing

* Narrow down all the outcomes/exposures 

#### Order of operations

* Clean data, do some exploration, modeling

* Plots - quick and easy ones, ones that are most informative to others
  - visualizations would augment more specific modeling that may be helpful 

#### Regression diagnostics

* Fit reasonable models - limits number of models we can fit - normally distributed errors, helps narrow things down

* look at residuals

* didn't overfit (outliers?)

If binary outcome: Most frequently observed outcomes are the best powered, most likely to find associations 

Confounders: Arguement to have w/ or w/o data - things to consider 


#### Other notes

leaflet package - looks like googlemaps 






