---
title: "P8105 Final Project - Group AAAD"
author: "Anjile An, Ashley Kang, Amelia Grant-Alfieri, Divya Bisht"
date: 'Due December 11, 2018'
output: github_document
---

#### The group members (names and UNIs)

Anjile An, ja3237 
<br>
Ashley Kang, aik2136
<br>
Amelia Grant-Alfieri, ag3911
<br>
Divya Bisht, db3180


#### The tentative project title

Fine Particulate Matter and Asthma and CVD ER Hospitalizations in NYC, 2012-2014.


#### The motivation for this project

We are interested in how environmental determinants of health, especially the short term effects of air quality measures across boroughs on acute health outcomes such as asthma and cardiovascular disease hospitalizations. This also helps us understand the burden of acute health outcomes especially given our changing climate. We hope our results will help illustrate potential health disparities within and across boroughs and thus areas requiring future research.

#### The intended final products

A webpage that details motivations, data sources, methods, results, and conclusions and future directions with 2-3 graphs detailing the relationship between air quality (PM concentration) and acute health outcomes (asthma and CVD). This page is also intended to be a resource for people looking to get more information on the effects of air pollutants on health in New York City, and be able to provide useful takeaways accesible to people outside of our class as well.

A screencast explaining in further detail our motivations and research questions, as well as modeling how we anticipate people interact with our webiste, especially in the interactivity of our visualizations.

#### The anticipated data sources

[New York City Open Data](https://opendata.cityofnewyork.us/)

[New York State Health Data](https://healthdata.ny.gov/browse)

[NYC Environmental Health Portal](http://a816-dohbesp.nyc.gov/IndicatorPublic/PublicTracking.aspx)

#### The planned analyses / visualizations / coding challenges

We plan to clean and tidy the data before running descriptive statistics to get a better understanding of the variables and sense of the distributions or patterns within our dataset. We also plan to visually assess our data to check for outliers, skewness, and other potential distributional patterns that may affect our further analyses.

Then we plan to do statistical analysis to address the association between air quality and health outcomes, including potential confounders and effect measure modifiers. We also hope to map our data in a meaningful way to visually communicate our findings. 

#### The planned timeline

**November 8 by 1:00** - Form a team and submit a proposal	written proposal document.

* Initial group meeting November 7th to finalize proposal.

**November 12-16** - Project review meeting

* Check group schedules to find a time, email assigned TA to set up project review meeting.
* Scheduling caveat: Amelia is away starting Nov 15th afternoon.

**December 6 by 4:00** - Report, written report giving detailed project description (as a GitHub repo)

* Divy up responsibilities, have everything done by December 4th so we can review each other's work and proofread before submission, debug, etc.

**December 6 by 4:00** - Webpage and screencast, webpage overview of project, with short explanatory video (published online)

* Write script and practice speaking your own section before group filming, familiarize yourself with working site, remember to upload to YouTube. 

**December 6 by 8:00**	- Peer assessment, brief assessment of your teammates contributions (as a short document)

* Complete peer assessment.

**December 11** -	“In class” discussion of projects

  * Meet before class to prep and run through presentation, potential questions, etc.
  * Be prepared to answer questions about your choices in analysis/visualizations, research questions, stylistic choices. 

